project:
  name: @project.artifactId@
  version: @project.version@

server:
  port: 8080
  # Enabling the below error to always will support returning error message parameter while using ApiException custom exp class
  error:
    include-message: always
  
logging:
  level:
    com.sundar.*: 'DEBUG'
